### ISSUE TITLE
(back-end) Implementar proteção de rotas com autorização de usuário.

### ISSUE THREAD

**Issue by aguirresabino** [lyndemberg/quebus#21]
- [x] Implementar middleware que fará a autorização de acesso às rotas.

- [ ] Implementar error handler global.

**Comment by aguirresabino** [comment]
error handler não é necessário neste momento, pode ser adicionado em uma próxima versão do sistema. O que acha @lyndemberg?

**Comment by lyndemberg** [comment]
sim, podemos deixar para a próxima versão então!
