### ISSUE TITLE
(back-end) adicionar um método no endpoint de pergunta que lista todas as perguntas de um usuário

### ISSUE THREAD

**Issue by lyndemberg** [lyndemberg/quebus#22]

**Comment by aguirresabino** [comment]
Para @lyndemberg 

As rotas para os recursos /v1/user e /v1/question tiveram os métodos refatorados para que utilizem query params.

Se desejar buscar questões de um usuário, por exemplo, utilize:

/v1/question?user={id}

Ou, se desejar buscar usuários pelo gênero, faça:

/v1/user?gender={gender}
